// Bundled Syriac audio map — generated by Syriac.IO TTS
// Index matches SYRIAC_LETTERS order in alphabet-data.ts

import type { AVPlaybackSource } from "expo-av";

export const SYR_LETTER_AUDIO: AVPlaybackSource[] = [
  require("../assets/audio/syr/letters/letter_0.wav"),
  require("../assets/audio/syr/letters/letter_1.wav"),
  require("../assets/audio/syr/letters/letter_2.wav"),
  require("../assets/audio/syr/letters/letter_3.wav"),
  require("../assets/audio/syr/letters/letter_4.wav"),
  require("../assets/audio/syr/letters/letter_5.wav"),
  require("../assets/audio/syr/letters/letter_6.wav"),
  require("../assets/audio/syr/letters/letter_7.wav"),
  require("../assets/audio/syr/letters/letter_8.wav"),
  require("../assets/audio/syr/letters/letter_9.wav"),
  require("../assets/audio/syr/letters/letter_10.wav"),
  require("../assets/audio/syr/letters/letter_11.wav"),
  require("../assets/audio/syr/letters/letter_12.wav"),
  require("../assets/audio/syr/letters/letter_13.wav"),
  require("../assets/audio/syr/letters/letter_14.wav"),
  require("../assets/audio/syr/letters/letter_15.wav"),
  require("../assets/audio/syr/letters/letter_16.wav"),
  require("../assets/audio/syr/letters/letter_17.wav"),
  require("../assets/audio/syr/letters/letter_18.wav"),
  require("../assets/audio/syr/letters/letter_19.wav"),
  require("../assets/audio/syr/letters/letter_20.wav"),
  require("../assets/audio/syr/letters/letter_21.wav"),
];

export const SYR_WORD_AUDIO: AVPlaybackSource[] = [
  require("../assets/audio/syr/words/word_0.wav"),
  require("../assets/audio/syr/words/word_1.wav"),
  require("../assets/audio/syr/words/word_2.wav"),
  require("../assets/audio/syr/words/word_3.wav"),
  require("../assets/audio/syr/words/word_4.wav"),
  require("../assets/audio/syr/words/word_5.wav"),
  require("../assets/audio/syr/words/word_6.wav"),
  require("../assets/audio/syr/words/word_7.wav"),
  require("../assets/audio/syr/words/word_8.wav"),
  require("../assets/audio/syr/words/word_9.wav"),
  require("../assets/audio/syr/words/word_10.wav"),
  require("../assets/audio/syr/words/word_11.wav"),
  require("../assets/audio/syr/words/word_12.wav"),
  require("../assets/audio/syr/words/word_13.wav"),
  require("../assets/audio/syr/words/word_14.wav"),
  require("../assets/audio/syr/words/word_15.wav"),
  require("../assets/audio/syr/words/word_16.wav"),
  require("../assets/audio/syr/words/word_17.wav"),
  require("../assets/audio/syr/words/word_18.wav"),
  require("../assets/audio/syr/words/word_19.wav"),
  require("../assets/audio/syr/words/word_20.wav"),
  require("../assets/audio/syr/words/word_21.wav"),
];
